on: [workflow_dispatch, push]

jobs:
  format:
    if: github.actor == 'Dobby233Liu'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v1
    - run: git pull --rebase
    - run: pip install black
    - run: |
        python -m black **/*.py || true
        python -m black *.py
    - continue-on-error: true
      env:
        ACTOR: ${{ github.actor }}
        GH_EMAIL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ACTOR_EMAIL=$(curl -H "Authorization: token $GH_EMAIL_TOKEN" "https://api.github.com/users/$ACTOR" --silent | sed -nE 's#^.*"email": "([^"]+)",.*$#\1#p')
        CMSG="[skip ci] routine formatting\n\
        \n\
        \n\
        Co-authored-by: $ACTOR <$ACTOR_EMAIL>"
        printf "$CMSG"
        git commit -am "$CMSG"
        git push
