name: Automated CSV Generation

on:
  push:
  pull_request:
  schedule:
    - cron: '5 22 * * *'
  workflow_dispatch:
jobs:
  generate-csv:
    name: Generate CSVs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: [de_dilbert, dilbert, drabble, garfield]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: wget http://john.ccac.rwth-aachen.de:8000/ftp/dilbert/${{ matrix.file }}.txt
        working-directory: ${{ runner.temp }}

      # cp1250 -sig utf-8
      #- run: python enc_convert.py ${{ runner.temp }}/${{ matrix.file }}.txt ${{ matrix.file }}.txt cp858 utf-8
      - run: iconv -f ISO8859-15 -t UTF-8 ${{ runner.temp }}/${{ matrix.file }}.txt > ${{ matrix.file }}.txt
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.file }}.txt
          name: original

      - run: python main.py ${{ matrix.file }}.txt ${{ matrix.file }}.csv
      - continue-on-error: true
        run: python sanitize.py ${{ matrix.file }}.csv

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.file }}.csv
          name: ${{ matrix.file }}
      - run: |
          sha256sum ${{ matrix.file }}.txt ${{ matrix.file }}.csv > ${{ matrix.file }}.sha256
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.file }}.sha256
          name: hashes
  deploy-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    # only run on that branch
    if: github.ref == 'refs/heads/main'
    needs: [generate-csv]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: static
      - working-directory: static
        run: |
          mv original/* .
          mv hashes/* .
          mv */*.csv .
          touch .nojekyll
      - run: |
          sudo apt install pandoc
          pandoc README.md -f markdown -t html -s -o static/index.html
      # I use bot creds so this
      - uses: Dobby233Liu/github-pages-deploy-action@dev-no-crap
        with:
          branch: gh-pages
          folder: static
